In [2]:
print("Hello World!")

Hello World!


In [3]:
import sys, torch
print(sys.executable)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))


/usr/bin/python3
CUDA available: False


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# 00. PyTorch Fundamentals

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Intro to tensors
### Creating tensors

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim # 0
scalar.item()

7

In [8]:
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [9]:
vector.ndim # 1
vector.shape # [3]

torch.Size([3])

In [10]:
matrix = torch.tensor([
    [7,8],
    [9,10]
])

In [11]:
matrix[0][1] # 8
matrix[1] # 9, 10
matrix.shape # [2,2]

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([
    [[1, 2, 3],
    [3, 6, 9],
    [2, 5, 4]],
    [[6, 7, 6],
    [7, 6, 7],
    [6, 7, 7]],
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]],

        [[6, 7, 6],
         [7, 6, 7],
         [6, 7, 7]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor[1]

tensor([[6, 7, 6],
        [7, 6, 7],
        [6, 7, 7]])

In [14]:
# scalars and vector names should be lowercase, matrix and tensor uppercase

### Other tensors

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7361, 0.7014, 0.1398, 0.2864],
        [0.8780, 0.3770, 0.9745, 0.8643],
        [0.3425, 0.5251, 0.0765, 0.1937]])

In [16]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
zero_tensor = torch.zeros(size=(3,4))
zero_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.tensor([0,1,1,1]) * random_tensor

tensor([[0.0000, 0.7014, 0.1398, 0.2864],
        [0.0000, 0.3770, 0.9745, 0.8643],
        [0.0000, 0.5251, 0.0765, 0.1937]])

In [19]:
zero_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

In [20]:
torch.arange(0,10, step=2)

tensor([0, 2, 4, 6, 8])

In [21]:
one_to_ten = torch.arange(0,11)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)
float_32_tensor

# Common errors when working with PyTorch:
# 1. Wrong datatype
# 2. Wrong tensor shape
# 3. Wrong device

tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

`dtype` -> `tensor.dtype`

`shape` -> `tensor.shape`

`device` -> `tensor.device`

In [27]:
some_tensor = torch.rand(3,4)
some_tensor, some_tensor.dtype, some_tensor.shape, some_tensor.device

(tensor([[0.5946, 0.1438, 0.5119, 0.8256],
         [0.2260, 0.4241, 0.9363, 0.1621],
         [0.3397, 0.8296, 0.2253, 0.8033]]),
 torch.float32,
 torch.Size([3, 4]),
 device(type='cpu'))

### Matrix manipulation

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10, tensor - 10, torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([11, 12, 13]))

In [30]:
# Manual matrix multiplication
a = torch.rand(3,3)
b = torch.rand(3,3)
c = torch.zeros(3,3)

# c = a * b

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c[i][j] = a[i][j] * b[j][i] # element-wise

c = torch.zeros(3,3)

for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        for k in range(c.shape[0]):
            c[i][j] += a[i][k] * b[k][j] # matrix multiplication
a, b, c

(tensor([[0.1042, 0.8422, 0.4868],
         [0.4381, 0.7287, 0.2462],
         [0.4971, 0.5454, 0.3008]]),
 tensor([[0.2247, 0.1291, 0.0077],
         [0.1981, 0.4960, 0.7917],
         [0.8685, 0.5319, 0.9657]]),
 tensor([[0.6130, 0.6901, 1.1376],
         [0.4566, 0.5490, 0.8181],
         [0.4810, 0.4947, 0.7261]]))

In [31]:
# Equivalently:
c = torch.matmul(a, b)
c

tensor([[0.6130, 0.6901, 1.1376],
        [0.4566, 0.5490, 0.8181],
        [0.4810, 0.4947, 0.7261]])

Rules for matrix multiplication:
1. The **inner dimensions** must match, i.e. `(m,n) * (n,m)`
2. The resulting matrix has the shape of the **outer dimensions**,
i.e. `(m,n) * (n,m)` -> `(n,n)`

In [32]:
torch.matmul(torch.tensor([[1,2],[1,2],[1,2]]), torch.tensor([[2,3,4],[2,3,4]]))

tensor([[ 6,  9, 12],
        [ 6,  9, 12],
        [ 6,  9, 12]])

In [33]:
torch.tensor([[1,2],[1,2],[1,2]]).shape, torch.tensor([[2,3,4],[2,3,4]]).shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [34]:
# Shapes for matrix multiplication
A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

B = torch.tensor([[7, 10],
                  [8, 11],
                  [9, 12]]).T

# Manual transpose
C = torch.zeros_like(B.T) # lil shortcut to flip dimensions
for i in range(B.shape[0]):
    for j in range(B.shape[1]):
        C[j][i] = B[i][j]

torch.mm(A, B) # .mm() is the same as .matmul()

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Matrix operations

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), x.min(), torch.max(x), x.max(), x.argmax()
# torch.mean(x) throws a dtype error

(tensor(0), tensor(0), tensor(90), tensor(90), tensor(9))

In [37]:
torch.mean(x.type(torch.float32))

tensor(45.)

Reshaping - reshpaes an input tensor to a defined shape

View - return a view of an input tensor of a certain shape but keeps the same memory as the original tensor

Stacking - combines multiple tensor on top of (vstack) or next to (hstack) each other

Squeeze - removes all `1` dimensions from a tensor

Unsqueeze - add a `1` dimension to a tensor

Permute - return a view of the input with dimensions permuted in a certain way

In [38]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [48]:
z = x.view(1,9)
# Changing z changes x (z and x share the same loc in memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, torch.stack([x,x,x,x], dim=1)

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

In [64]:
torch.vstack([x,x,x,x])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped, x_reshaped.squeeze()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
x_original = torch.rand(size=(224, 224, 3))

x_original.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

In [83]:
x_original[:,:,0]

tensor([[0.7734, 0.0678, 0.5250,  ..., 0.9672, 0.0020, 0.4942],
        [0.7346, 0.2426, 0.8257,  ..., 0.8970, 0.5472, 0.8077],
        [0.8984, 0.4056, 0.4864,  ..., 0.2147, 0.2600, 0.4908],
        ...,
        [0.9747, 0.4759, 0.7629,  ..., 0.5763, 0.0195, 0.7100],
        [0.1584, 0.5465, 0.2587,  ..., 0.7433, 0.8061, 0.1856],
        [0.0157, 0.2010, 0.3291,  ..., 0.2528, 0.1651, 0.0568]])

In [87]:
# Indexing with PyTorch is similar to indexing with NumPy
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
x[0][2][1]
# Can use : to select all of a target dimension

tensor(8)

## PyTorch tensors & NumPy

Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [105]:
import numpy as np

array = np.arange(1.0, 8.0) # float64 default
tensor = torch.from_numpy(array) # .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [106]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [107]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [108]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [110]:
RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C, random_tensor_D

(tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]),
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]))

### Check for GPU access


```!nvidia-smi```

```{pytorch}
import torch
torch.cuda.is_available()
```

```{python}
device = "cuda" if torch.cuda.is_available() else "cpu"
# device is a param for torch.tensor
```

In [112]:
tensor = torch.tensor([1,2,3], device="cpu")

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device) # should change to GPU if available

In [120]:
tensor_on_gpu.numpy() # will throw an error because cuda-type device tensors cannot be converted to numpy arrays
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])