In [2]:
print("Hello World!")

Hello World!


In [3]:
import sys, torch
print(sys.executable)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))


/usr/bin/python3
CUDA available: False


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# 00. PyTorch Fundamentals

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Intro to tensors
### Creating tensors

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim # 0
scalar.item()

7

In [8]:
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [9]:
vector.ndim # 1
vector.shape # [3]

torch.Size([3])

In [10]:
matrix = torch.tensor([
    [7,8],
    [9,10]
])

In [11]:
matrix[0][1] # 8
matrix[1] # 9, 10
matrix.shape # [2,2]

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([
    [[1, 2, 3],
    [3, 6, 9],
    [2, 5, 4]],
    [[6, 7, 6],
    [7, 6, 7],
    [6, 7, 7]],
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]],

        [[6, 7, 6],
         [7, 6, 7],
         [6, 7, 7]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor[1]

tensor([[6, 7, 6],
        [7, 6, 7],
        [6, 7, 7]])

In [14]:
# scalars and vector names should be lowercase, matrix and tensor uppercase

### Other tensors

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0378, 0.4017, 0.9950, 0.2107],
        [0.2603, 0.2774, 0.1460, 0.8708],
        [0.5622, 0.4807, 0.5032, 0.9131]])

In [16]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
zero_tensor = torch.zeros(size=(3,4))
zero_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.tensor([0,1,1,1]) * random_tensor

tensor([[0.0000, 0.4017, 0.9950, 0.2107],
        [0.0000, 0.2774, 0.1460, 0.8708],
        [0.0000, 0.4807, 0.5032, 0.9131]])

In [19]:
zero_tensor.dtype, random_tensor.dtype

(torch.float32, torch.float32)

In [20]:
torch.arange(0,10, step=2)

tensor([0, 2, 4, 6, 8])

In [21]:
one_to_ten = torch.arange(0,11)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, 
                               device=None,
                               requires_grad=False)
float_32_tensor

# Common errors when working with PyTorch:
# 1. Wrong datatype
# 2. Wrong tensor shape
# 3. Wrong device

tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

`dtype` -> `tensor.dtype`

`shape` -> `tensor.shape`

`device` -> `tensor.device`

In [27]:
some_tensor = torch.rand(3,4)
some_tensor, some_tensor.dtype, some_tensor.shape, some_tensor.device

(tensor([[0.6776, 0.6701, 0.2025, 0.9509],
         [0.7797, 0.4077, 0.1400, 0.6894],
         [0.8668, 0.9922, 0.2441, 0.7064]]),
 torch.float32,
 torch.Size([3, 4]),
 device(type='cpu'))

### Matrix manipulation

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10, tensor - 10, torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([11, 12, 13]))

In [30]:
# Manual matrix multiplication
a = torch.rand(3,3)
b = torch.rand(3,3)
c = torch.zeros(3,3)

# c = a * b

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c[i][j] = a[i][j] * b[j][i] # element-wise

c = torch.zeros(3,3)

for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        for k in range(c.shape[0]):
            c[i][j] += a[i][k] * b[k][j] # matrix multiplication
a, b, c

(tensor([[0.8502, 0.0946, 0.8020],
         [0.4657, 0.3779, 0.3387],
         [0.9231, 0.9162, 0.3483]]),
 tensor([[0.9025, 0.0840, 0.4876],
         [0.0328, 0.4500, 0.1033],
         [0.6150, 0.0789, 0.7146]]),
 tensor([[1.2637, 0.1773, 0.9975],
         [0.6410, 0.2359, 0.5082],
         [1.0774, 0.5173, 0.7937]]))

In [31]:
# Equivalently:
c = torch.matmul(a, b)
c

tensor([[1.2637, 0.1773, 0.9975],
        [0.6410, 0.2359, 0.5082],
        [1.0774, 0.5173, 0.7937]])

Rules for matrix multiplication:
1. The **inner dimensions** must match, i.e. `(m,n) * (n,m)`
2. The resulting matrix has the shape of the **outer dimensions**,
i.e. `(m,n) * (n,m)` -> `(n,n)`

In [32]:
torch.matmul(torch.tensor([[1,2],[1,2],[1,2]]), torch.tensor([[2,3,4],[2,3,4]]))

tensor([[ 6,  9, 12],
        [ 6,  9, 12],
        [ 6,  9, 12]])

In [33]:
torch.tensor([[1,2],[1,2],[1,2]]).shape, torch.tensor([[2,3,4],[2,3,4]]).shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [34]:
# Shapes for matrix multiplication
A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

B = torch.tensor([[7, 10],
                  [8, 11],
                  [9, 12]]).T

# Manual transpose
C = torch.zeros_like(B.T) # lil shortcut to flip dimensions
for i in range(B.shape[0]):
    for j in range(B.shape[1]):
        C[j][i] = B[i][j]

torch.mm(A, B) # .mm() is the same as .matmul()

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Matrix operations

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.min(x), x.min(), torch.max(x), x.max(), x.argmax()
# torch.mean(x) throws a dtype error

(tensor(0), tensor(0), tensor(90), tensor(90), tensor(9))

In [46]:
torch.mean(x.type(torch.float32))

tensor(45.)